environment.name: Development

info.app.name: ^project.artifactId^
info.app.version: ^project.version^

management:
  health.diskspace.enabled: false
  endpoints:
    web.base-path: /manage
    web.exposure.include: '*'
    web.exposure.exclude: shutdown, heapdump
  endpoint.health.show-details: always
  metrics:
    export:
      graphite:
        enabled: true
        host: localhost
        port: 2003
        step: 1m
        protocol: plaintext
        duration-units: milliseconds
        rate-units: seconds
